source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
target 'test' do
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

#   # Pods for test
#   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
#   pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
#   pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
#   pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
#   pod 'React', :path => '../node_modules/react-native/'
#   pod 'React-Core', :path => '../node_modules/react-native/'
#   pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#   pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
#   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
#   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
#   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#   # Firebase Instant Push Notifications
#   pod 'Firebase/Core'
#   pod 'Firebase/Messaging'
#   # React Native third party dependencies podspecs
#   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#   # Don't remove the follwing magic comment (see https://facebook.github.io/react-native/docs/linking-libraries-ios.html)
#   # Add new pods below this line
#   # React Native Permissions dependencies
#   permissions_path = '../node_modules/react-native-permissions/ios'
#   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
#   pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
#   pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
#   pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
#   pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
#   # React Native Maps dependencies
#   rn_maps_path = '../node_modules/react-native-maps'
#   pod 'react-native-google-maps', :path => rn_maps_path
#   pod 'GoogleMaps'
#   pod 'Google-Maps-iOS-Utils'
  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end