source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'test' do
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    target 'testTests' do
        inherit! :search_paths
        # Pods for testing
    end

    # use_native_modules!
end